def generate_error_message(exception):
    return {
            "status" : False,
            "message" : str(exception)
        }